POST http://localhost:8080/jee/api/payments
Content-Type: application/json
Accept: application/xml

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/jee/api/payments/bb5e0d69-5103-4f05-b0e3-4ffeec209a71
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/jee/api/payments/confirmed
Content-Type: application/json
Accept: application/json
